// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0wW542s0ezRg4WFRnpthgtSO_EZtlIjw',
    appId: '1:245292429740:web:2c39fa140da403d4718a09',
    messagingSenderId: '245292429740',
    projectId: 'athangexpense',
    authDomain: 'athangexpense.firebaseapp.com',
    storageBucket: 'athangexpense.appspot.com',
    measurementId: 'G-VN65TJJEY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_8T99XP9D3eBmVAlSV3s9Kq8bmrfPsK8',
    appId: '1:245292429740:android:8afec1a3b0f49367718a09',
    messagingSenderId: '245292429740',
    projectId: 'athangexpense',
    storageBucket: 'athangexpense.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq16wgdKIlCiJ-TeAv56dGO3qCP9mhpgg',
    appId: '1:245292429740:ios:0749bfcf25a5347f718a09',
    messagingSenderId: '245292429740',
    projectId: 'athangexpense',
    storageBucket: 'athangexpense.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq16wgdKIlCiJ-TeAv56dGO3qCP9mhpgg',
    appId: '1:245292429740:ios:0749bfcf25a5347f718a09',
    messagingSenderId: '245292429740',
    projectId: 'athangexpense',
    storageBucket: 'athangexpense.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0wW542s0ezRg4WFRnpthgtSO_EZtlIjw',
    appId: '1:245292429740:web:2363dd581b0b1e03718a09',
    messagingSenderId: '245292429740',
    projectId: 'athangexpense',
    authDomain: 'athangexpense.firebaseapp.com',
    storageBucket: 'athangexpense.appspot.com',
    measurementId: 'G-8C4TYBMYPY',
  );

}